name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
    branches: ["**"]

permissions:
  contents: read # for golangci-lint-action

jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        os: [Ubuntu]
        go-version: ["1.24.x"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
